name: Deploy to GCP EC2
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using remote ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/Wen/GROUP1-BE
            git pull origin main
            docker stop projectcapsContainer
            docker rm projectcapsContainer
            docker rmi projectcaps-images:latest
            docker build -t projectcaps-images:latest .
            docker run -d -p 80:80 -e CONFIG_SMTP_HOST=${{ secrets.CONFIG_SMTP_HOST }} -e CONFIG_SMTP_PORT=${{ secrets.CONFIG_SMTP_PORT }} -e CONFIG_SENDER_NAME=${{ secrets.CONFIG_SENDER_NAME }} -e CONFIG_AUTH_PASSWORD=${{ secrets.CONFIG_AUTH_PASSWORD }} -e CONFIG_AUTH_EMAIL=${{ secrets.CONFIG_AUTH_EMAIL }} -e DB_Username=${{ secrets.DB_USERNAME }} -e DB_Password=${{ secrets.DB_PASSWORD }} -e DB_Port=${{ secrets.DB_PORT }} -e DB_Host=${{ secrets.DB_HOST }} -e DB_Name=${{ secrets.DB_NAME }} -e DB_BUCKET=${{ secrets.DB_BUCKET }} -e DB_SECRET=${{ secrets.DB_SECRET }} --name projectcapsContainer projectcaps-images:latest
